# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eada2e8dc16217a6e0259d0e97884b552c3cdb0ed9c00c098a226b0a4df3217834217301b95e6704f90676a7eb7e842f84393509d89b7ddfc2e69d84b68ed99f

test:
  secret_key_base: 20ad61b587b6c6254693f0260dc6c2a3d11eacbb6a873de088f3aabc27b7d4a701707aeca94720358a68860706c0993d38339b42dbb42c982c2d8d64901ef0e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
